musicapp/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user, login_required
from musicapp.models import Song, Playlist
from musicapp.songs.forms import SearchForm

main = Blueprint('main', __name__)


@main.context_processor
def layout():
    form = SearchForm()
    return dict(form=form)


@main.route('/')
@main.route('/home')
@login_required
def home():
    page = request.args.get('page', 1, type=int)
    songs = Song.query.filter_by(
        owner_id=current_user.id).paginate(page=page, per_page=12)
    return render_template('home.html', songs=songs)


@main.route('/collection')
@login_required
def collection():
    songs_page = request.args.get('songs_page', 1, type=int)
    playlists_page = request.args.get('playlists_page', 1, type=int)
    songs = Song.query.paginate(page=songs_page, per_page=12)
    playlists = Playlist.query.paginate(page=playlists_page, per_page=5)
    return render_template('collection.html', title='All Songs', songs=songs, playlists=playlists)

musicapp/songs/routes.py
import requests
from flask import request, jsonify
import os
from flask import render_template, url_for, flash, redirect, request, send_file, abort, Blueprint, request, jsonify, current_app as app
from flask_login import current_user, login_required
from sqlalchemy import or_
from sqlalchemy.exc import SQLAlchemyError
import eyed3

from musicapp.models import Song, Artist_info, User, Like, Comment, Reply, Playlist
from musicapp import db
from musicapp.songs.forms import SongForm, SearchForm, SongMetadataForm, CommentForm, ReplyForm, PlaylistForm
from musicapp.songs.utils import save_song, search_music
from musicapp.artist.routes import delete_artist
import base64
from werkzeug.utils import secure_filename

import requests

songs = Blueprint('songs', __name__)


@songs.context_processor
def layout():
    form = SearchForm()
    return dict(form=form)


@songs.route('/song/upload', methods=['GET', 'POST'])
@login_required
def upload():
    form = SongForm()
    if form.validate_on_submit():
        song_file = form.song.data
        filename = save_song(song_file)
        file_path = os.path.join(
            app.config['UPLOAD_FOLDER'], filename)
        audio = eyed3.load(file_path)
        title = audio.tag.title if audio.tag.title else "Unknown Title"
        artist = audio.tag.artist if audio.tag.artist else "Unknown Artist"
        album = audio.tag.album if audio.tag.album else "Unknown Album"
        song = Song(title=title, artist=artist,
                    album=album, owner=current_user, filename=filename)
        db.session.add(song)
        try:
            db.session.commit()
        except SQLAlchemyError:
            db.session.rollback()
            os.remove(file_path)
            flash('Error uploading song, retry', 'danger')
            return redirect(url_for('songs.upload'))
        return redirect(url_for('songs.song_metadata', id=song.id))
    return render_template('upload_song.html', title='Upload Song', form=form)


# @songs.route('/song/upload/metadata/<int:id>', methods=['GET', 'POST'])
# @login_required
# def song_metadata(id):
#     form = SongMetadataForm()
#     song = Song.query.get_or_404(id)
#     if song.owner != current_user:
#         abort(403)

#     if form.validate_on_submit():
#         song.title = form.title.data
#         song.artist = form.artist.data
#         song.album = form.album.data
#         db.session.commit()

#         song_path = os.path.join(
#             app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
#         audio = eyed3.load(song_path)
#         audio.tag.title = song.title
#         audio.tag.artist = song.artist
#         audio.tag.album = song.album
#         audio.tag.save()

#         flash(f'Song `{form.title.data}` has been uploaded!', 'success')
#         return redirect(url_for('songs.upload'))
#     elif request.method == 'GET':
#         form.title.data = song.title
#         form.artist.data = song.artist
#         form.album.data = song.album
#     return render_template('song_metadata.html', title='Edit song details', form=form)

# @songs.route('/song/upload/metadata/<int:id>', methods=['GET', 'POST'])
# @login_required
# def song_metadata(id):
#     form = SongMetadataForm()
#     song = Song.query.get_or_404(id)
#     if song.owner != current_user:
#         abort(403)

#     if form.validate_on_submit():
#         title = form.title.data if form.title.data else "Unknown Title"
#         artist = form.artist.data if form.artist.data else "Unknown Artist"
#         album = form.album.data if form.album.data else "Unknown Album"

#         if title == "Unknown Title" or artist == "Unknown Artist" or album == "Unknown Album":
#             song_path = os.path.join(
#                 app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
#             os.remove(song_path)  # delete the file
#             db.session.delete(song)  # delete the song record
#             db.session.commit()
#             flash('Please provide a title, artist, and album.', 'danger')
#             return redirect(url_for('songs.upload'))
#         else:
#             song.title = title
#             song.artist = artist
#             song.album = album
#             db.session.commit()

#             song_path = os.path.join(
#                 app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
#             audio = eyed3.load(song_path)
#             audio.tag.title = title
#             audio.tag.artist = artist
#             audio.tag.album = album
#             audio.tag.save()

#             flash(f'Song `{title}` has been uploaded!', 'success')
#             return redirect(url_for('songs.upload'))
#     elif request.method == 'GET':
#         form.title.data = song.title
#         form.artist.data = song.artist
#         form.album.data = song.album
#     return render_template('song_metadata.html', title='Edit song details', form=form)

@songs.route('/song/upload/metadata/<int:id>', methods=['GET', 'POST'])
@login_required
def song_metadata(id):
    form = SongMetadataForm()
    song = Song.query.get_or_404(id)
    if song.owner != current_user:
        abort(403)

    if form.validate_on_submit():
        title = form.title.data if form.title.data else "Unknown Title"
        artist_name = form.artist.data if form.artist.data else "Unknown Artist"
        album = form.album.data if form.album.data else "Unknown Album"

        if title == "Unknown Title" or artist_name == "Unknown Artist" or album == "Unknown Album":
            song_path = os.path.join(
                app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
            os.remove(song_path)  # delete the file
            db.session.delete(song)  # delete the song record
            db.session.commit()
            flash('Please provide a title, artist, and album.', 'danger')
            return redirect(url_for('songs.upload'))
        else:
            artist_info = Artist_info.query.filter_by(name=artist_name).first()

            # If the artist doesn't exist, create a new Artist_info
            if artist_info is None:
                artist_info = Artist_info(name=artist_name)
                db.session.add(artist_info)
                db.session.commit()

            song.title = title
            song.artist = artist_name
            song.artist_id = artist_info.id  # set the artist_id to the id of the artist_info
            song.album = album
            db.session.commit()

            song_path = os.path.join(
                app.root_path, app.config['UPLOAD_FOLDER'], song.filename)
            audio = eyed3.load(song_path)
            audio.tag.title = title
            audio.tag.artist = artist_name
            audio.tag.album = album
            audio.tag.save()

            flash(f'Song `{title}` has been uploaded!', 'success')
            return redirect(url_for('songs.upload'))
    elif request.method == 'GET':
        form.title.data = song.title
        form.artist.data = song.artist  # get the name of the artist
        form.album.data = song.album
    return render_template('song_metadata.html', title='Edit song details', form=form, filename=song.filename)


# @songs.route('/song/play/<int:song_id>')
# @login_required
# def song(song_id):
#     song = Song.query.get_or_404(song_id)
#     song_file = url_for('static', filename='uploads/' + song.filename)
#     songs = Song.query.order_by(Song.id).all()
#     next_song = Song.query.filter(Song.id > song_id).first()
#     prev_song = Song.query.filter(
#         Song.id < song_id).order_by(Song.id.desc()).first()
#     return render_template('song.html', song=song, music=song_file, songs=songs, next_song=next_song, prev_song=prev_song)

@songs.route('/song/play/<int:song_id>', methods=['GET', 'POST'])
@login_required
def song(song_id):
    song = Song.query.get_or_404(song_id)
    song_file = url_for('static', filename='uploads/' + song.filename)
    songs = Song.query.order_by(Song.id).all()
    next_song = Song.query.filter(Song.id > song_id).first()
    prev_song = Song.query.filter(
        Song.id < song_id).order_by(Song.id.desc()).first()

    # Query for likes, comments, and replies
    likes = Like.query.filter_by(song_id=song_id).all()
    comments = Comment.query.filter_by(
        song_id=song_id).order_by(Comment.id.desc()).all()
    replies = Reply.query.join(Comment, (Reply.comment_id == Comment.id)).filter(
        Comment.song_id == song_id).all()

    # Create forms for likes, comments, and replies
    comment_form = CommentForm()
    reply_form = ReplyForm()

    return render_template('song.html', song=song, music=song_file, songs=songs, next_song=next_song, prev_song=prev_song,
                           likes=likes, comments=comments, replies=replies,
                           comment_form=comment_form, reply_form=reply_form)


@songs.route('/song/edit/<int:song_id>', methods=['GET', 'POST'])
@login_required
def edit(song_id):
    form = SongMetadataForm()
    song = Song.query.get_or_404(song_id)
    if song.owner != current_user and not current_user.is_admin and not current_user.is_manager:
        abort(403)

    if form.validate_on_submit():
        title = form.title.data if form.title.data else "Unknown Title"
        artist_name = form.artist.data if form.artist.data else "Unknown Artist"
        album = form.album.data if form.album.data else "Unknown Album"

        artist_info = Artist_info.query.filter_by(name=artist_name).first()

        # If the artist doesn't exist, create a new Artist_info
        if artist_info is None:
            artist_info = Artist_info(name=artist_name)
            db.session.add(artist_info)
            db.session.commit()

        # delete old artist if no songs are associated with him/her
        delete_artist(song.artist_id)
        song.title = title
        song.artist = artist_name
        song.artist_id = artist_info.id  # set the artist_id to the id of the artist_info
        song.album = album

musicapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, logout_user, current_user, login_required
from musicapp.models import User
from musicapp import bcrypt, db
from musicapp.users.forms import RegistrationForm, LoginForm, UpdateAccountForm, RequestResetForm, ResetPasswordForm
from musicapp.users.utils import send_password_reset_email

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user = User(username=form.username.data,
                    email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Account Successfully Created! Please login to continue.', 'success')
        return redirect(url_for('users.login'))

    return render_template('register.html', title='Register', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        flash('Login Failed! Please check email and password.', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('users.login'))


@users.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    return render_template('account.html', title='Account', form=form)


@users.route('/reset_password', methods=['GET', 'POST'])
def password_reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_password_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('password_reset_request.html', title="Reset Password", form=form)


@users.route('/reset_password/<string:token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))

    user = User.verify_reset_token(token)
    if user is None:
        flash('Token is invalid or expired!', 'warning')
        return redirect(url_for('users.password_reset_request'))

    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(
            form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! Please login to continue.', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_password.html', title="Reset Password", form=form)


@users.route('/admin')
@login_required
def admin():
    if not (current_user.is_admin):
        flash('You are not an admin!', 'danger')
        return redirect(url_for('main.home'))

    users = User.query.all()
    return render_template('admin/admin.html', title='Admin', users=users)


@users.route('/admin/confirm_delete/<int:user_id>/<string:username>', methods=['POST'])
@login_required
def confirm_delete(user_id, username):
    if not (current_user.is_admin):
        flash('You are not an admin!', 'danger')
        return redirect(url_for('main.home'))

    return render_template('admin/confirm_delete.html', title='Confirm Delete', user_id=user_id, username=username)


@users.route('/admin/delete/<int:user_id>', methods=['POST'])
@login_required
def delete(user_id):
    if not (current_user.is_admin):
        flash('You are not an admin!', 'danger')
        return redirect(url_for('main.home'))

    user = User.query.get_or_404(user_id)
    # only admin can delete user
    if user.is_admin or user.is_manager:
        flash('You cannot delete admin or manager!', 'danger')
        return redirect(url_for('users.admin'))

    user_username = user.username

    # delete the user from database
    db.session.delete(user)
    db.session.commit()

    flash(f'User `{user_username}` has been deleted!', 'success')
    return redirect(url_for('users.admin'))


@users.route('/admin/grant_manager/<int:user_id>', methods=['POST'])
@login_required
def grant_manager(user_id):
    if not (current_user.is_admin):
        flash('You are not an admin!', 'danger')
        return redirect(url_for('main.home'))

    user = User.query.get_or_404(user_id)

    user.is_manager = True
    db.session.commit()

    flash(f'User `{user.username}` has been granted manager!', 'success')
    return redirect(url_for('users.admin'))


@users.route('/admin/revoke_manager/<int:user_id>', methods=['POST'])
@login_required
def revoke_manager(user_id):
    if not (current_user.is_admin):
        flash('You are not an admin!', 'danger')
        return redirect(url_for('main.home'))

    user = User.query.get_or_404(user_id)
    if user.is_admin:
        flash('You cannot revoke admin!', 'danger')
        return redirect(url_for('users.admin'))

    user.is_manager = False
    db.session.commit()

    flash(f'User `{user.username}` has been revoked manager!', 'success')
    return redirect(url_for('users.admin'))

musicapp/templates/search_results.html
{% extends "layout.html" %}
{% block content %}
  {% if songs %}
    <legend class="border-bottom mb-4">
      Search results for '{{ search_input_text }}'
    </legend>
    <table class="table">
      <thead>
        <tr>
          <th scope="col">#</th>
          <th scope="col">Title</th>
          <th scope="col">Artist</th>
          <th scope="col">Album</th>
        </tr>
      </thead>
      <tbody>
        {% for song in songs %}
          <tr class="my-4">
            <td scope="row">{{ loop.index }}</td>
            <td>
              <a href="{{ url_for('songs.song', song_id=song.id) }}"
                 class="song-body text-decoration-none">{{ song.title }}</a>
            </td>
            <td>{{ song.artist }}</td>
            <td>{{ song.album }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% else %}
    <h2>No results found for "{{ search_input_text }}"</h2>
    <p class="text-muted">Please try searching something else!</p>
  {% endif %}
{% endblock content %}

musicapp/templates/song.html
{% extends "layout.html" %} {% block content %} {% if song %}
<article class="media content-section" style="display: flex">
    <div class="media-body">
        <div
            class="container"
            style="display: flex; justify-content: space-between">
            <div class="article-metadata" style="flex: 7; position: relative">
                <div style="display: flex; justify-content: space-between; align-items: baseline;">
                    <legend class="mb-1">
                        {{ song.title }}
                    </legend>
                    <!-- like count -->
                    <legend class="right-align"><span id="like-count">{{ song.likes.count() }}</span>💓</legend>
                </div>
                <p class="text-muted">
                    By
                    <a
                        href="{{ url_for('artists.artist_info', artist_id=song.artist_id) }}"
                        ><strong>{{ song.artist }}</strong></a
                    >
                    <br />
                    From <strong>{{ song.album }}</strong>
                </p>
                <!-- edit and like button -->
                <div>
                    {% if song.owner == current_user or current_user.is_admin or current_user.is_manager %}
                    <form action="{{ url_for('songs.edit', song_id=song.id) }}" method="get">
                        <button type="submit" class="edit-button">Edit</button>
                    </form>
                    {% endif %}
                    <form id="like-form" class="right-align" action="{{ url_for('songs.like', song_id=song.id) }}" method="post" style="display: block;">
                        {% if song.is_liked_by(current_user) %}
                        <button id="like-button" type="submit" class="btn btn-primary">Unlike</button>
                        {% else %}
                        <button id="like-button" type="submit" class="btn btn-primary">Like</button>
                        {% endif %}
                    </form>
                </div>
            </div>
            <div
                class="container"
                style="
                    flex: 3;
                    display: flex;
                    justify-content: center;
                    align-items: center;
                    margin: 5px;
                ">
                <img
                    src="{{ url_for('static', filename='Images/MusicLib_Logo.PNG') }}"
                    class="img-fluid"
                    style="border-radius: 10px" />
            </div>
        </div>

        <audio
            id="audioPlayer"
            controls
            autoplay
            controlslist="nodownload"
            class="w-100 mt-2 mb-2">
            <source src="{{ music }}" type="audio/mp3" />
            <source src="{{ music }}" type="audio/mpeg" />
            <source src="{{ music }}" type="audio/wav" />
            Your browser does not support the audio tag.
        </audio>
        <script>
            document.getElementById('audioPlayer').addEventListener('ended', function() {
                // Assuming song.id is available in the template context
                var nextSongId = {{ song.id }} + 1;
                var baseUrl = "{{ url_for('songs.song', song_id=1) }}";
                var nextSongUrl = baseUrl.slice(0, baseUrl.lastIndexOf('/') + 1) + nextSongId;
                window.location.href = nextSongUrl;
            }, false);
        </script>
        <div class="song-controls">
            <div class="prev-song">
                {% if prev_song %}
                <a
                    class="btn btn-outline-info song-control"
                    href="{{ url_for('songs.song', song_id=prev_song.id) }}">
                    <i class="fas fa-chevron-left"></i> Previous Song
                </a>
                {% endif %}
            </div>
            <div class="next-song">
                {% if next_song %}
                <a
                    class="btn btn-outline-info song-control"
                    href="{{ url_for('songs.song', song_id=next_song.id) }}">
                    Next Song <i class="fas fa-chevron-right"></i>
                </a>
                {% endif %}
            </div>
        </div>
        <div class="btns">
            <a
                class="btn btn-outline-info"
                href="{{ url_for('songs.download', song_id = song.id) }}"
                >Download</a
            >
            {% if song.owner == current_user or current_user.is_admin or
            current_user.is_manager %}
            <button
                type="button"
                class="btn btn-outline-danger m-2"
                data-bs-toggle="modal"
                data-bs-target="#deleteModalCenter">
                Delete
            </button>
            {% endif %}
        </div>
        <!-- query button -->
        <button id="detect-button" class="btn btn-outline-info">Detect Music</button>

        <!-- song info display area -->
        <div id="song-info"></div>
        <div class="article-metadata" style="flex: 7; position: relative">
            <legend class="mb-1">Related Songs</legend>
            <ul class="song-list">
                {% for next_song in songs %}
                <li>
                    <a
                        class="song-link"
                        href="{{ url_for('songs.song', song_id=next_song.id) }}"
                        >{{ next_song.title }}</a
                    >
                </li>
                {% endfor %}
            </ul>
        </div>
    </div>
</article>

<!-- query function -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script>
$("#detect-button").click(function() {
    console.log("Button clicked");
    var filename = "{{ song.filename }}";
    console.log("Filename: " + filename);
    $.ajax({
        url: '/detect_music',
        type: 'POST',
        data: { 'filename': filename },
        success: function(data) {
            var songInfo = document.getElementById('song-info');
            if (data.result) {
                songInfo.innerHTML = 'Title: ' + data.result.title + ', Artist: ' + data.result.artist;
                if (data.result.album) {
                    songInfo.innerHTML += ', Album: ' + data.result.album;
                }
                if (data.result.release_date) {
                    songInfo.innerHTML += ', Release Date: ' + data.result.release_date;
                }
                if (data.result.song_link) {
                    songInfo.innerHTML += ', <a href="' + data.result.song_link + '">Song Link</a>';
                }
                if (data.result.apple_music && data.result.apple_music.url) {
                    songInfo.innerHTML += ', <a href="' + data.result.apple_music.url + '">Apple Music Link</a>';
                }
                if (data.result.spotify && data.result.spotify.external_urls && data.result.spotify.external_urls.spotify) {
                    songInfo.innerHTML += ', <a href="' + data.result.spotify.external_urls.spotify + '">Spotify Link</a>';
                }
            } else {
                songInfo.innerHTML = 'Cannot find';
            }
        }
    });
});
</script>
<!-- Modal -->
<div
    class="modal fade"
    id="deleteModalCenter"
    tabindex="-1"
    aria-labelledby="deleteModalCenterTitle"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModalLongTitle">
                    Delete Song?
                </h5>
                <button
                    type="button"
                    class="btn-close"
                    data-bs-dismiss="modal"
                    aria-label="Close"></button>
            </div>
            <div class="modal-footer">
                <button
                    type="button"
                    class="btn btn-secondary"
                    data-bs-dismiss="modal">
                    Close
                </button>
                <form
                    action="{{ url_for('songs.delete', song_id=song.id) }}"
                    method="post">
                    <input
                        type="submit"
                        class="btn btn-danger"
                        value="Delete" />
                </form>
            </div>
        </div>
    </div>
</div>
<!-- like script -->
<script>
    $(document).ready(function() {
        $('#like-form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                url: "{{ url_for('songs.like', song_id=song.id) }}",
                method: 'POST',
                success: function(response) {
                    if (response.liked) {
                        $('#like-button').text('Unlike');
                    } else {
                        $('#like-button').text('Like');
                    }
                    $('#like-count').text(response.like_count);
                }
            });
            return false;
        });
    });
</script>
<!-- Comment form -->
<form id="comment-form" action="{{ url_for('songs.comment', song_id=song.id) }}" method="post" class="mt-3">
    <div class="input-group">
        <textarea name="text" class="form-control" placeholder="Write a comment..." required></textarea>
        <button type="submit" class="btn btn-primary">Comment</button>
    </div>
</form>
<script>
    $(document).ready(function() {
        $('#comment-form').submit(function(e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('action'),
                method: 'POST',
                data: $(this).serialize(),
                success: function(response) {
                    // Add the new comment to the comments section
                    var comment = $(
                        '<div class="card mb-3">' +
                            '<div class="card-body">' +
                                '<h5 class="card-title">' + response.user.username + '</h5>' +
                                '<p class="card-text">' + response.text + '</p>' +
                            '</div>' +
                        '</div>'
                    );
                    $('#comments').prepend(comment);
                    // Clear the comment form
                    $('#comment-form textarea[name="text"]').val('');
                }
            });
        });
    });
</script>
<!-- Comments -->
<div id="comments">
    {% for comment in comments %}
    <div class="card mb-3">
        <div class="card-body">
            <h4 class="card-title"><strong>{{ comment.user.username }}</strong></h4>
            <p class="card-text">{{ comment.text }}</p>
            <button class="show-replies btn btn-primary">Show/Hide Replies</button>
            <!-- Replies -->
            <div id="replies-{{ comment.id }}" class="replies">
                {% for reply in comment.replies %}
                <div class="card mt-3 ml-5">
                    <div class="card-body">
                        <h6 class="card-title">{{ reply.user.username }}</h6>
                        <p class="card-text">{{ reply.text }}</p>
                    </div>
                </div>
                {% endfor %}
            </div>

            <!-- Reply form -->
            <form id="reply-form-{{ comment.id }}" action="{{ url_for('songs.reply', comment_id=comment.id) }}" method="post" class="mt-3">
                <div class="input-group">
                    <textarea name="text" class="form-control" placeholder="Write a reply..." required></textarea>
                    <button type="submit" class="btn btn-primary">Reply</button>
                </div>
            </form>
        </div>
    </div>
    {% endfor %}
</div>
<!-- show replies func -->
<script>
$(document).ready(function() {
    $('form[id^="reply-form-"]').submit(function(e) {
        e.preventDefault();
        var formId = $(this).attr('id');
        var commentId = formId.split('-')[2];
        $.ajax({
            url: $(this).attr('action'),
            method: 'POST',
            data: $(this).serialize(),
            success: function(response) {
                // Add the new reply to the replies section
                var reply = $(
                    '<div class="card mt-3 ml-5">' +
                        '<div class="card-body">' +
                            '<h6 class="card-title">' + response.user.username + '</h6>' +
                            '<p class="card-text">' + response.text + '</p>' +
                        '</div>' +
                    '</div>'
                );
                $('#replies-' + commentId).prepend(reply);
                // Clear the reply form
                $('#reply-form-' + commentId + ' textarea[name="text"]').val('');
            }
        });
    });
});
$(document).ready(function() 
{
        $('.show-replies').click(function() {
            $(this).nextAll('.replies').first().toggle();
        });
});
</script>
{% else %}
<h2>Song does not exist!</h2>
<p class="text-muted">Try to play other songs.</p>
{% endif %} {% endblock content %}